### ISSUE TITLE
Refactor in favor of Adapter pattern

### ISSUE THREAD

**Issue by ms5984** [Cronuside/PersistentDataUtilities#1]
See [website](https://sourcemaking.com/design_patterns/adapter).
From my understanding, this utility is designed to help cut down on SLOC involved when working with the PersistentDataContainer interface in two particular circumstances: Players, and ItemStacks.

This library object might benefit from is storing the NamespacedKey within itself; this would allow the user to instantiate the utility with the key baked in, and perform the operations they want (has, store values, etc) with respect to that key.

```java
new PersistentDataUtils(myKey).getPlayerInt(Player); // makes use of object model
// versus
new PersistentDataUtils().getPlayerInt(myKey, Player); // could be refactored as static as-is
// after refactor -> PersistentDataUtils.getPlayerInt(Player)
```

**Comment by Cronuside** [comment]
Thank you very much for this input. I've gone ahead and refactored my code to implement this feedback!

**Comment by ms5984** [comment]
Np!
